// pages/index.jsx

import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import styles from "../styles/Home.module.css";

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }
    return { props };
  },
  sessionOptions
);

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Bookmarked</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Reading made simple.
        </h1>
        {props.isLoggedIn ? (
          <Link href="/search">
            <button className={styles.getStartedButton}>Start browsing →</button>
          </Link>
        ) : (
          <Link href="/login">
            <button className={styles.getStartedButton}>Get Started →</button>
          </Link>
        )}
      </main>

      <Footer />
    </div>
  );
}
