import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";
import Footer from "../components/footer";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
//import styles from "../styles/Home.module.css";



export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }
    return { props };
  },
  sessionOptions
);

export default function Home(props) {
 
  return ( //fix later
    <div>
      <Head>
        <title>Bookmarked</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />

      <main >
        <h1 >
          Welcome to Bookmarked!
        </h1>

      </main>

      <Footer/>
    </div>
    )
}