import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { useState } from "react";
import { useRouter } from "next/router";
import styles from "../styles/signup.module.css";  

export default function Signup(props) {
  const router = useRouter();
  const [
    { username, password, "confirm-password": confirmPassword },
    setForm,
  ] = useState({
    username: "",
    password: "",
    "confirm-password": "",
  });
  const [error, setError] = useState("");

  function handleChange(e) {
    setForm({
      username,
      password,
      "confirm-password": confirmPassword,
      ...{ [e.target.name]: e.target.value.trim() },
    });
  }

  async function handleCreateAccount(e) {
    e.preventDefault();
    if (!username) return setError("Must include username");
    if (password !== confirmPassword) return setError("Passwords must match");

    try {
      const res = await fetch("/api/auth/signup", {
        method: "POST",
        headers: {
          "content-type": "application/json",
        },
        body: JSON.stringify({ username, password }),
      });
      if (res.status === 200) return router.push("/");
      const { error: message } = await res.json();
      setError(message);
    } catch (err) {
      console.log(err);
    }
  }

  return (
    <div>
      <Header isLoggedIn={props.isLoggedIn} />
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Let's get started.</h1>

        <form className={styles.formContainer} onSubmit={handleCreateAccount}>
          <label className={styles.label} htmlFor="username">Username: </label>
          <input
            className={styles.inputField}
            type="text"
            name="username"
            id="username"
            onChange={handleChange}
            value={username}
          />
          <label className={styles.label} htmlFor="password">Password: </label>
          <input
            className={styles.inputField}
            type="password"
            name="password"
            id="password"
            onChange={handleChange}
            value={password}
          />
          <label className={styles.label} htmlFor="confirm-password">Confirm Password: </label>
          <input
            className={styles.inputField}
            type="password"
            name="confirm-password"
            id="confirm-password"
            onChange={handleChange}
            value={confirmPassword}
          />
          <button className={styles.button}>Let's go</button>
          {error && <p className={styles.error}>{error}</p>}
        </form>
        <Link href="/login">
          <p className={styles.link}>Login instead?</p>
        </Link>
      </main>
      <Footer />
    </div>
  );
}
